import React, {
  createContext,
  ReactNode,
  SetStateAction,
  useContext,
  useEffect,
  useState,
} from 'react';

// Generated by https://quicktype.io

export interface User {
  id: string;
}

export interface IResponseLogin {
  user: User;
  accessToken: string;
  refreshToken: string;
}
interface IUserProvider {
  user: User;
  setUser: React.Dispatch<SetStateAction<User>>;
  isAuthenticated: () => boolean;
  logout: () => void;
}

interface ChildrenProps {
  children: ReactNode;
}

const AuthContext = createContext({} as IUserProvider);

const AuthProvider = ({ children }: ChildrenProps) => {
  const [user, setUser] = useState<User>({} as User);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const dataUser = localStorage.getItem('@TGS: user');

    if (dataUser) {
      setUser(JSON.parse(dataUser));
    }
    setLoading(false);
  }, []);

  const isAuthenticated = () => {
    return user.id !== undefined;
  };

  const logout = () => {
    localStorage.removeItem('@TGS: user');
    localStorage.removeItem('@TGS: accessToken');
    localStorage.removeItem('@TGS: refreshToken');
    setUser({} as User);
  };

  if (loading) {
    return null;
  }

  return (
    // eslint-disable-next-line react/jsx-no-constructed-context-values
    <AuthContext.Provider value={{ user, setUser, isAuthenticated, logout }}>
      {children}
    </AuthContext.Provider>
  );
};

export default AuthProvider;

export const useAuth = () => useContext(AuthContext);
